# Generated by Django 4.0.4 on 2022-06-04 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=10000)),
                ('Age', models.CharField(max_length=10000)),
                ('Gender', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=10000)),
                ('Price', models.CharField(max_length=10000)),
                ('Producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_page.people')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Doctor', models.CharField(max_length=10000)),
                ('Hospital', models.CharField(max_length=10000)),
                ('Patient', models.ManyToManyField(to='index_page.people')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Biography', models.CharField(max_length=10000)),
                ('Biographer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index_page.people')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=10000)),
                ('Owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index_page.people')),
            ],
        ),
    ]
