# Generated by Django 4.0.4 on 2022-06-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Company', models.CharField(max_length=10000)),
                ('Address', models.CharField(max_length=10000)),
                ('Owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index_page.people')),
            ],
        ),
        migrations.AddField(
            model_name='bio',
            name='Name_of_Family',
            field=models.CharField(default='Okezie', max_length=10000),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
