# Generated by Django 4.0.4 on 2022-06-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0002_addres_bio_name_of_family_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='Name_of_Family',
            field=models.CharField(max_length=10000),
        ),
    ]
