# Generated by Django 4.0.4 on 2022-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='Room_Type',
            field=models.CharField(default='Family Room', max_length=100),
        ),
    ]
