# Generated by Django 4.0.4 on 2022-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='Room_Type',
            field=models.CharField(max_length=100),
        ),
    ]
