# Generated by Django 4.0.4 on 2022-06-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_alter_guest_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deluxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=10000)),
                ('Occupation', models.CharField(max_length=10000)),
                ('Room_Category', models.CharField(default='Executive', max_length=100)),
                ('Room_Type', models.CharField(max_length=100)),
                ('Room_Number', models.IntegerField()),
                ('Amount_Paid', models.CharField(max_length=100)),
                ('Number_of_Nights', models.IntegerField()),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=10000)),
                ('Occupation', models.CharField(max_length=10000)),
                ('Room_Category', models.CharField(default='Executive', max_length=100)),
                ('Room_Type', models.CharField(max_length=100)),
                ('Room_Number', models.IntegerField()),
                ('Amount_Paid', models.CharField(max_length=100)),
                ('Number_of_Nights', models.IntegerField()),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=10000)),
                ('Occupation', models.CharField(max_length=10000)),
                ('Room_Category', models.CharField(default='Executive', max_length=100)),
                ('Room_Type', models.CharField(max_length=100)),
                ('Room_Number', models.IntegerField()),
                ('Amount_Paid', models.CharField(max_length=100)),
                ('Number_of_Nights', models.IntegerField()),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
