# Generated by Django 4.0.4 on 2022-06-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_deluxe_executive_standard_delete_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deluxe',
            name='Room_Category',
            field=models.CharField(default='Deluxe', max_length=100),
        ),
        migrations.AlterField(
            model_name='standard',
            name='Room_Category',
            field=models.CharField(default='Standard', max_length=100),
        ),
    ]
