# Generated by Django 4.0.4 on 2022-06-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_alter_deluxe_room_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deluxe',
            new_name='Guest',
        ),
        migrations.DeleteModel(
            name='Executive',
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
    ]
