# Generated by Django 4.0.4 on 2022-06-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_rename_deluxe_guest_delete_executive_delete_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='Room_Category',
            field=models.CharField(max_length=100),
        ),
    ]
