# Generated by Django 4.0.4 on 2022-06-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_rename_guest_guests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guests',
            new_name='Guest',
        ),
    ]
