# Generated by Django 4.0.4 on 2022-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occupant_Name', models.CharField(max_length=100)),
                ('Occupant_Email', models.CharField(max_length=10000)),
                ('Occupant_Occupation', models.EmailField(max_length=10000)),
                ('Amount_Paid', models.CharField(max_length=100)),
                ('Room_Number', models.IntegerField(max_length=20)),
                ('Number_of_Nights', models.IntegerField(max_length=10000)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
    ]
