# Generated by Django 4.0.4 on 2022-06-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_guest_number_of_nights_alter_guest_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='Number_of_Nights',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='Room_Number',
            field=models.IntegerField(),
        ),
    ]
